hymaintenance/customers/models/user.py
hymaintenance/customers/tests/models/test_user.py
hymaintenance/high_ui/templates/high_ui/company_details_header.html
hymaintenance/high_ui/templates/high_ui/dashboard_header.html
hymaintenance/high_ui/templates/high_ui/issue_details.html
hymaintenance/high_ui/templates/high_ui/issue_details_header.html
hymaintenance/high_ui/templates/high_ui/user_header.html
hymaintenance/high_ui/views/base.py
hymaintenance/high_ui/views/dashboard.py
hymaintenance/high_ui/views/users/update_profile.py

Fixes #348 
* add user permissions functions in MaintenanceUser
* add tests on the functions

Refs 348, add user has permissions functions

---

hymaintenance/high_ui/templates/high_ui/company_details.html

Fixes #352 
!! READ BEFORE https://github.com/HybirdCorp/HyMaintenance/pull/350 !! because it uses one of the new user permissions functions.

Niouby 352 remove update credit link

---

hymaintenance/high_ui/templates/high_ui/admin.html

Refs 353, remove email alert in admin page

---

hymaintenance/high_ui/templates/high_ui/forms/base_issue.html

Refs 351, fix consumer and operator initial value in issue_update_form

---

hymaintenance/high_ui/tests/views/test_credit_view.py
hymaintenance/high_ui/urls.py
hymaintenance/high_ui/views/credit.py

Fixes #316 
* add delete credits url and view
* add test on delete credits feature

Refs 316, add delete credits feature and tests

---

hymaintenance/customers/models/company.py
hymaintenance/customers/tests/models/test_company.py

Refs 359, fix update slug_name only when company name changes

---

hymaintenance/customers/forms/project.py
hymaintenance/customers/tests/forms/test_company_forms.py
hymaintenance/high_ui/templates/high_ui/admin.html
hymaintenance/high_ui/templates/high_ui/forms/archive_projects.html
hymaintenance/high_ui/templates/high_ui/forms/unarchive_projects.html
hymaintenance/high_ui/templates/high_ui/forms/update_projects.html
hymaintenance/high_ui/tests/views/test_dashboard.py
hymaintenance/high_ui/tests/views/test_project_views.py
hymaintenance/high_ui/urls.py
hymaintenance/high_ui/views/admin.py
hymaintenance/high_ui/views/base.py
hymaintenance/high_ui/views/project.py

Fixes #310 
Fixes #308 
* display archived and active projects on admin page
* add archive/unarchive form
* add archive/unarchive url, views and templates
* add tests on the new feature
* fix bug on company_number on dashboard header, which count archived projects

Niouby 310 display archived project

---

hymaintenance/high_ui/static/css/form.css
hymaintenance/high_ui/static/js/segmented-selector.js
hymaintenance/high_ui/templates/high_ui/forms/base_credit.html
hymaintenance/high_ui/templates/high_ui/forms/create_credit.html
hymaintenance/high_ui/templates/high_ui/forms/update_credit.html
hymaintenance/maintenance/forms/credit.py

Fixes #366 
* modify segmented_selector to provide a custom value
* add a custom value on create/update credits forms

Refs 366, modify segmented_selector to have a custom-value field

---

hymaintenance/high_ui/templates/high_ui/admin.html
hymaintenance/high_ui/templates/high_ui/forms/unarchive_issues.html
hymaintenance/high_ui/templatetags/print_fields.py
hymaintenance/high_ui/tests/views/test_issue_views.py
hymaintenance/high_ui/urls.py
hymaintenance/high_ui/views/issue.py
hymaintenance/maintenance/forms/issue.py
hymaintenance/maintenance/tests/forms/test_issue_forms.py

Fixes #312 
* add issue unarchive form
* add issue url view and template unarchive form
* add test on the new form and view

Niouby 312 reactivate deleted issue

---

hymaintenance/customers/forms/company.py
hymaintenance/customers/tests/factories.py
hymaintenance/customers/tests/forms/test_company_forms.py
hymaintenance/high_ui/tests/views/test_project_views.py
hymaintenance/maintenance/forms/project.py
hymaintenance/maintenance/tests/forms/test_project_forms.py

!! Read https://github.com/HybirdCorp/HyMaintenance/pull/389 before !!
Fixes #388

Niouby 388 bug

---

hymaintenance/high_ui/templates/high_ui/dashboard.html
hymaintenance/high_ui/templates/high_ui/dashboard_header.html

!!! read before https://github.com/HybirdCorp/HyMaintenance/pull/389 then https://github.com/HybirdCorp/HyMaintenance/pull/390 !!!
Fixes #387 
* hide administrator feature on dashboard to operators

Niouby 387 hide forbidden buttons

---

hymaintenance/high_ui/templates/high_ui/forms/base_project.html

!! read https://github.com/HybirdCorp/HyMaintenance/pull/394 before !!
Fixes #395

Niouby 395 bug js project form

---

hymaintenance/high_ui/views/dashboard.py
hymaintenance/maintenance/models/contract.py

Refs 295, fix project and counter order on dashboard

---

requirements.txt

Ref 402, update django

---

hymaintenance/high_ui/templates/high_ui/company_details_header.html
hymaintenance/high_ui/tests/views/test_project_views.py
hymaintenance/maintenance/models/contract.py

Niouby 404 manager button

---

hymaintenance/high_ui/tests/views/test_email_alert_view.py
hymaintenance/high_ui/views/project.py

Niouby 405 contract email alert

---

hymaintenance/high_ui/tests/views/users/test_update_profile.py

propose une autre façon de tester previous_page contenu dans le get_context_data

Niouby 369 remove onclick v1.1

---

hymaintenance/high_ui/static/js/fast_click.js
hymaintenance/high_ui/templates/high_ui/forms/base_consumer.html
hymaintenance/high_ui/templates/high_ui/forms/base_credit.html
hymaintenance/high_ui/templates/high_ui/forms/base_issue.html
hymaintenance/high_ui/templates/high_ui/forms/base_project.html
hymaintenance/high_ui/templates/high_ui/forms/create_user.html
hymaintenance/high_ui/templates/high_ui/forms/customize_project.html
hymaintenance/high_ui/templates/high_ui/forms/unarchive_issues.html
hymaintenance/high_ui/templates/high_ui/forms/update_credit_choices.html
hymaintenance/high_ui/templates/high_ui/forms/update_email_alert.html
hymaintenance/high_ui/templates/high_ui/forms/update_infos.html
hymaintenance/high_ui/templates/high_ui/forms/update_list_base.html
hymaintenance/high_ui/templates/high_ui/forms/update_maintenance_type.html
hymaintenance/high_ui/templates/high_ui/forms/update_projects.html
hymaintenance/high_ui/templates/high_ui/forms/update_user.html
hymaintenance/high_ui/templates/high_ui/forms/update_users.html

Niouby 371 remove fast click

---

hymaintenance/high_ui/templates/high_ui/forms/create_admin.html
hymaintenance/high_ui/templates/high_ui/forms/create_company_operator.html
hymaintenance/high_ui/templates/high_ui/forms/create_consumer.html
hymaintenance/high_ui/templates/high_ui/forms/create_manager.html
hymaintenance/high_ui/templates/high_ui/forms/create_operator.html
hymaintenance/high_ui/views/users/create_user.py

Refs 428, fix back page link in create user form

---

hymaintenance/high_ui/templates/high_ui/forms/base_project.html
hymaintenance/high_ui/templates/high_ui/forms/create_project.html
hymaintenance/high_ui/templates/high_ui/forms/update_project.html

Refs 424, fix counter name display in update project form

---

hymaintenance/maintenance/models/credit.py
hymaintenance/maintenance/tests/models/test_credit.py

Niouby 413 post delete credited hours

---

hymaintenance/customers/models/company.py
hymaintenance/high_ui/templates/high_ui/admin.html
hymaintenance/high_ui/tests/views/test_admin_views.py
hymaintenance/high_ui/views/issue.py

Refs 422, remove link to unarchive_issue when any archived issue

---

hymaintenance/high_ui/templates/high_ui/company_details_header.html
hymaintenance/high_ui/templates/high_ui/forms/base_credit.html
hymaintenance/high_ui/templates/high_ui/forms/update_credit.html
hymaintenance/high_ui/tests/views/test_project_views.py
hymaintenance/high_ui/views/project.py

Niouby 447 missing links

---

hymaintenance/high_ui/templates/high_ui/forms/base_issue.html
hymaintenance/high_ui/templates/high_ui/forms/update_issue.html
hymaintenance/maintenance/forms/issue.py

Niouby 438 bug issue form

---

hymaintenance/high_ui/templates/high_ui/forms/base_credit.html
hymaintenance/high_ui/tests/views/test_credit_view.py
hymaintenance/maintenance/forms/credit.py
hymaintenance/maintenance/tests/forms/test_credit_forms.py

Niouby 429 date create credit form

---

hymaintenance/high_ui/tests/views/test_perfs.py
hymaintenance/high_ui/urls.py

add queries perfs tests on all views and reorganize urls order

add queries perfs tests on all views

---

hymaintenance/high_ui/templates/high_ui/company_details_header.html
hymaintenance/high_ui/tests/views/test_perfs.py
hymaintenance/high_ui/views/base.py
hymaintenance/maintenance/models/contract.py

improve perf by adding maintenance_type select_related on company

Niouby fix perf mtype

---

hymaintenance/high_ui/templates/high_ui/admin.html
hymaintenance/high_ui/tests/views/test_perfs.py
hymaintenance/high_ui/views/admin.py

improve admin perf on link to unarchive issue form when the project has archived issues.

Niouby fix perf on admin view

---

.circleci/config.yml
hymaintenance/high_ui/templates/high_ui/forms/base_issue.html
hymaintenance/high_ui/templates/high_ui/forms/update_users.html
hymaintenance/hymaintenance/settings.py
hymaintenance/maintenance/tests/forms/test_project_forms.py
hymaintenance/requirements/develop.in
hymaintenance/requirements/develop.txt
hymaintenance/requirements/requirements.in
hymaintenance/requirements/requirements.txt

merge this PR before https://github.com/HybirdCorp/HyMaintenance/pull/481

Update django to 3.2

---

hymaintenance/high_ui/templates/high_ui/admin.html
hymaintenance/high_ui/tests/views/test_admin_views.py
hymaintenance/high_ui/tests/views/test_perfs.py
hymaintenance/high_ui/views/admin.py

bug introduce by this commit https://github.com/HybirdCorp/HyMaintenance/commit/1832293ba11d9775830035eecd8ca3b92df97e81

fix projects and users numbers in admin view

---

hymaintenance/hymaintenance/settings.py
hymaintenance/requirements/develop.txt
hymaintenance/requirements/requirements.in
hymaintenance/requirements/requirements.txt

Refs https://hytickets.hybird.org/tickets/HyMt-2

HyM-2 - setup sentry in settings

---

hymaintenance/customers/tests/forms/test_company_forms.py
hymaintenance/high_ui/templates/high_ui/forms/base_project.html
hymaintenance/high_ui/templates/high_ui/forms/create_project.html
hymaintenance/high_ui/templates/high_ui/forms/update_maintenance_type.html
hymaintenance/high_ui/templates/high_ui/forms/update_project.html
hymaintenance/high_ui/tests/views/test_credit_view.py
hymaintenance/high_ui/tests/views/test_maintenance_type_view.py
hymaintenance/high_ui/tests/views/test_perfs.py
hymaintenance/high_ui/tests/views/test_project_views.py
hymaintenance/high_ui/views/maintenance_type.py
hymaintenance/high_ui/views/users/update_profile.py
hymaintenance/high_ui/views/users/update_user.py
hymaintenance/maintenance/forms/other_models.py
hymaintenance/maintenance/forms/project.py
hymaintenance/maintenance/models/other_models.py
hymaintenance/maintenance/tests/forms/test_issue_forms.py
hymaintenance/maintenance/tests/forms/test_other_models_forms.py
hymaintenance/maintenance/tests/forms/test_project_forms.py

Refs https://hytickets.hybird.org/tickets/HyMt-6

HyT-6 - check and fix all possible array overflows
